/*
##########################
#  Hexadecimal Colors  # DEBES MODIFICAR LOS VALORES Y AÑADIR TUS PROPIOS COLORES #
##########################
*/

#define HCOL_SERVER     0xFFFFFFFF
#define HCOL_WHITE      0xFFFFFFFF
#define HCOL_BLACK      0xFFFFFFFF
#define HCOL_TMPGRAY    0xFFFFFFFF    

#define HCOL_MONEY      0xFFFFFFFF

#define HCOL_RED        0xFFFFFFFF
#define HCOL_GREEN      0xFFFFFFFF
#define HCOL_ORANGE     0xFFFFFFFF
#define HCOL_SKYBLUE    0xFFFFFFFF
#define HCOL_YELLOW     0xFFFFFFFF
#define HCOL_PINK       0xFFFFFFFF
#define HCOL_ERROR      0xFFFFFFFF

#define HCOL_ME         0xFFFFFFFF
#define HCOL_DO         0xFFFFFFFF

#define HCOL_ECODE      0xFFFFFFFF

/*
####################
#  CSS Colors  #
####################
*/

#define COL_SERVER      "{ffffff}"
#define COL_WHITE       "{ffffff}"
#define COL_BLACK       "{ffffff}"

#define COL_MONEY       "{ffffff}"
#define COL_RED         "{ffffff}"
#define COL_GREEN       "{ffffff}"
#define COL_ORANGE      "{ffffff}"
#define COL_SKYBLUE     "{ffffff}"
#define COL_YELLOW      "{ffffff}"
#define COL_PINK        "{ffffff}"
#define COL_ERROR       "{ffffff}"

#define COL_ME          "{ffffff}"
#define COL_DO          "{ffffff}"

#define COL_E_CODE      "{ffffff}"
/*
####################
#  Discord Colors  #
####################
*/

#define DC_COL_SERVER       16777215
#define DC_COL_WHITE        16777215
#define DC_COL_BLACK        16777215

#define DC_COL_MONEY       16777215
#define DC_COL_RED         16777215
#define DC_COL_GREEN       16777215
#define DC_COL_ORANGE      16777215
#define DC_COL_SKYBLUE     16777215
#define DC_COL_YELLOW      16777215
#define DC_COL_PURPLE      16777215
#define DC_COL_PINK        16777215
#define DC_COL_ERROR       16777215