/*
##########################
#  Hexadecimal Colors  #
##########################
*/

#define HCOL_SERVER     0xA82C23FF
#define HCOL_WHITE      0xFFFFFFFF
#define HCOL_BLACK      0x0F0F0FFF
#define HCOL_TMPGRAY    0x7D7D7DCC    

#define HCOL_MONEY      0x0B6E27FF

#define HCOL_RED        0xA70000FF
#define HCOL_GREEN      0x15851DFF
#define HCOL_ORANGE     0xC73B0CFF
#define HCOL_SKYBLUE    0x02A8ADFF
#define HCOL_YELLOW     0xBFBC08FF
#define HCOL_PINK       0xAD02C7FF
#define HCOL_ERROR      0x700101FF

#define HCOL_ME         0xACC97F22A
#define HCOL_DO         0x5a7b94FF

/*
####################
#  CSS Colors  #
####################
*/

#define COL_SERVER      "{a82c23}"
#define COL_WHITE       "{ffffff}"
#define COL_BLACK       "{0f0f0f}"

#define COL_MONEY       "{0b6e27}"
#define COL_RED         "{a70000}"
#define COL_GREEN       "{15851d}"
#define COL_ORANGE      "{c73b0c}"
#define COL_SKYBLUE     "{02a8ad}"
#define COL_YELLOW      "{bfbc08}"
#define COL_PINK        "{ad02c7}"
#define COL_ERROR       "{700101}"

#define COL_ME          "{cc97f2}"
#define COL_DO          "{5a7b94}"
/*
####################
#  Discord Colors  #
####################
*/

#define DC_COL_SERVER       11021347
#define DC_COL_WHITE        16777215
#define DC_COL_BLACK        986895

#define DC_COL_MONEY       749095
#define DC_COL_RED         10944512
#define DC_COL_GREEN       1410333
#define DC_COL_ORANGE      13056780
#define DC_COL_SKYBLUE     174253
#define DC_COL_YELLOW      12565512
#define DC_COL_PURPLE      6949055
#define DC_COL_PINK        11338439
#define DC_COL_ERROR       7340289